// Stripe price_id mapping — generated by stripeCreateCatalog (admin, one-time).
// Mirrors paymentCatalog.js: each external_reference maps to the Stripe Price
// that represents the same product. Used by stripeCreateCheckout to resolve
// the correct price_id and checkout mode (subscription vs payment).
//
// DO NOT edit by hand — re-run stripeCreateCatalog to regenerate if prices
// change in Stripe. The function is idempotent (reuses existing products/prices
// via metadata) so re-running won't create duplicates.
//
// mode: "subscription" → recurring monthly plan (plan:*)
// mode: "payment"     → one-time prepaid pack (pack:*)
export const STRIPE_CATALOG = {
  "plan:basic":    { price_id: "price_1U1y6gPuHVs0PU8YzCpk4hc3", mode: "subscription", product_id: "prod_V22BBhu55PoXX8" },
  "plan:standard": { price_id: "price_1U1y6hPuHVs0PU8YS6J8LjYO", mode: "subscription", product_id: "prod_V22B9fvvYpXu17" },
  "plan:premium":  { price_id: "price_1U1y6hPuHVs0PU8YpxZGLGhJ", mode: "subscription", product_id: "prod_V22BeB4uZO2yiQ" },
  "pack:pp_30":   { price_id: "price_1U1y6iPuHVs0PU8YPSvSDZnU", mode: "payment", product_id: "prod_V22BUcp3BtBENj" },
  "pack:pp_60":   { price_id: "price_1U1y6iPuHVs0PU8YbIi17n94", mode: "payment", product_id: "prod_V22BPDD4pRXfPk" },
  "pack:pp_120":  { price_id: "price_1U1y6iPuHVs0PU8YPVIG6s2C", mode: "payment", product_id: "prod_V22BP6jHXBTtvw" },
  "pack:pp_300":  { price_id: "price_1U1y6jPuHVs0PU8Y8gD9fpHw", mode: "payment", product_id: "prod_V22BJVSvy3WxsV" },
  "pack:pp_600":  { price_id: "price_1U1y6jPuHVs0PU8Yw6Ro16bs", mode: "payment", product_id: "prod_V22BvwdtZZDCHi" },
};

// Resolve the checkout mode from the external_reference prefix.
export function getStripeMode(externalReference) {
  const entry = STRIPE_CATALOG[externalReference];
  if (entry) return entry.mode;
  return externalReference.startsWith("plan:") ? "subscription" : "payment";
}