// Stripe price_id mapping — generated by stripeCreateCatalog (admin, one-time).
// Mirrors paymentCatalog.js: each external_reference maps to the Stripe Price
// that represents the same product. Used by stripeCreateCheckout to resolve
// the correct price_id and checkout mode (subscription vs payment).
//
// DO NOT edit by hand — re-run stripeCreateCatalog to regenerate if prices
// change in Stripe. The function is idempotent (reuses existing products/prices
// via metadata) so re-running won't create duplicates.
//
// INTERNATIONAL PRICING: each plan AND pack has a `prices` map with price_ids
// per currency (brl/eur/jpy/krw/usd). The BRL price_id is also kept as the
// top-level `price_id` for backward compatibility. `getStripePriceId(externalReference, currency)`
// resolves the right price_id for a given currency, falling back to BRL if the
// regional one isn't set yet. Pack `prices` maps start with only `brl` and get
// the other currencies filled in after the admin runs stripeCreateCatalog.
//
// mode: "subscription" → recurring monthly plan (plan:*)
// mode: "payment"     → one-time prepaid pack (pack:*)
export const STRIPE_CATALOG = {
  "plan:basic":    { price_id: "price_1U7dTRLrbgaxg9EVgX6Drynd", mode: "subscription", product_id: "prod_V6A6uyCQxsiiX1", prices: { brl: "price_1U7dTRLrbgaxg9EVgX6Drynd", eur: "price_1U7dTQLrbgaxg9EVzh1wRxqm", jpy: "price_1U7dTRLrbgaxg9EVFL1D7LjO", krw: "price_1U7dTRLrbgaxg9EVKGyoQ3H4", usd: "price_1U7dTRLrbgaxg9EVgX6Drynd" } },
  "plan:standard": { price_id: "price_1U7dTSLrbgaxg9EVfn3zqVlI", mode: "subscription", product_id: "prod_V6A6EqpSDVLc2p", prices: { brl: "price_1U7dTSLrbgaxg9EVfn3zqVlI", eur: "price_1U7dTRLrbgaxg9EVbR8ewDS7", jpy: "price_1U7dTRLrbgaxg9EVSgVrDy4i", krw: "price_1U7dTSLrbgaxg9EVX1nyVoa8", usd: "price_1U7dTSLrbgaxg9EVfn3zqVlI" } },
  "plan:premium":  { price_id: "price_1U7dTTLrbgaxg9EVyQxJVlLt", mode: "subscription", product_id: "prod_V6A65X2k2sRNoq", prices: { brl: "price_1U7dTTLrbgaxg9EVyQxJVlLt", eur: "price_1U7dTSLrbgaxg9EVaJtv9TnK", jpy: "price_1U7dTSLrbgaxg9EV6r8il6rz", krw: "price_1U7dTSLrbgaxg9EVaKFYnTmV", usd: "price_1U7dTTLrbgaxg9EVyQxJVlLt" } },
  "pack:pp_30":   { price_id: "price_1U5xmSLrbgaxg9EV3pwYcNNu", mode: "payment", product_id: "prod_V6A6AFfvDlruK9", prices: { brl: "price_1U5xmSLrbgaxg9EV3pwYcNNu", eur: "price_1U7h6HLrbgaxg9EVe0zHEcB4", jpy: "price_1U7h6HLrbgaxg9EVK3oU2fnC", krw: "price_1U7h6HLrbgaxg9EVcfSqxFw1", usd: "price_1U7h6HLrbgaxg9EVgOM5Z9LY" } },
  "pack:pp_60":   { price_id: "price_1U5xmTLrbgaxg9EVVKxtcvSL", mode: "payment", product_id: "prod_V6A6W96pVHh4kA", prices: { brl: "price_1U5xmTLrbgaxg9EVVKxtcvSL", eur: "price_1U7h6HLrbgaxg9EVyG5PqxW0", jpy: "price_1U7h6ILrbgaxg9EVJmUHljrD", krw: "price_1U7h6ILrbgaxg9EV2LWJgA5J", usd: "price_1U7h6ILrbgaxg9EV4bWfY2Ni" } },
  "pack:pp_120":  { price_id: "price_1U5xmTLrbgaxg9EV4U1TF2xR", mode: "payment", product_id: "prod_V6A6ZdjG7OQrlT", prices: { brl: "price_1U5xmTLrbgaxg9EV4U1TF2xR", eur: "price_1U7h6ILrbgaxg9EVoZQ7vZ4t", jpy: "price_1U7h6ILrbgaxg9EVLAUvWfoK", krw: "price_1U7h6JLrbgaxg9EVBZnwf9t5", usd: "price_1U7h6JLrbgaxg9EVoubX6IiZ" } },
  "pack:pp_300":  { price_id: "price_1U5xmTLrbgaxg9EVhi3iN6Dp", mode: "payment", product_id: "prod_V6A6Sw8FtADJuK", prices: { brl: "price_1U5xmTLrbgaxg9EVhi3iN6Dp", eur: "price_1U7h6JLrbgaxg9EVobkOSIPc", jpy: "price_1U7h6JLrbgaxg9EV7nBwY9oA", krw: "price_1U7h6JLrbgaxg9EVoZPuFJvI", usd: "price_1U7h6KLrbgaxg9EVNezZHiai" } },
  "pack:pp_600":  { price_id: "price_1U5xmULrbgaxg9EVJgeP8Piu", mode: "payment", product_id: "prod_V6A6DguxHWcmNW", prices: { brl: "price_1U5xmULrbgaxg9EVJgeP8Piu", eur: "price_1U7h6KLrbgaxg9EVEf0of9ci", jpy: "price_1U7h6KLrbgaxg9EVQ8C7EKAa", krw: "price_1U7h6KLrbgaxg9EVSugNacjN", usd: "price_1U7h6KLrbgaxg9EVk5mjf59K" } },
};

// Resolve the checkout mode from the external_reference prefix.
export function getStripeMode(externalReference) {
  const entry = STRIPE_CATALOG[externalReference];
  if (entry) return entry.mode;
  return externalReference.startsWith("plan:") ? "subscription" : "payment";
}

// Resolve the Stripe price_id for a given external_reference + currency.
// Falls back to the BRL price_id if the regional price hasn't been created yet
// (e.g. before stripeCreateCatalog has been run for international currencies).
export function getStripePriceId(externalReference, currency) {
  const entry = STRIPE_CATALOG[externalReference];
  if (!entry) return null;
  const c = String(currency || "").toLowerCase();
  if (!c || c === "brl") return entry.price_id;
  const regionalPriceId = entry.prices?.[c];
  if (regionalPriceId) return regionalPriceId;
  // Fallback to BRL if regional price not yet created.
  return entry.price_id;
}